### ISSUE TITLE
can not find compress package 

### ISSUE THREAD

**Issue by newyorkthink** [ivan-hc/KDE-utils-appimage#3]
when i use this command 
 ./Downloads/KDE_Utils_suite-22.12.3+5.142-x86_64.AppImage ark

is ok, good 

![image](https://github.com/ivan-hc/KDE-utils-appimage/assets/87791643/a604e606-5a4a-4261-9503-ed145f472aaa)

but i add the compress package in this command line , it show error, just ark sad cannot find this package

 ./Downloads/KDE_Utils_suite-22.12.3+5.142-x86_64.AppImage ark sd.7z
![image](https://github.com/ivan-hc/KDE-utils-appimage/assets/87791643/771b1e60-2528-45c7-8c76-a3c23a9f45c9)

**Comment by ivan-hc** [comment]
I don't know why all this stuff does not work for you, I'm able to compress files, play things (https://github.com/ivan-hc/Database-of-pkg2appimaged-packages/issues/3) and everything else.

Just curious, what is your system/distro?

**Comment by ivan-hc** [comment]
Sorry but please join the conversations, don't just post problems and then to tell me it's fixed, I can't always guess the solution to problems with the Appimages I produce. There are many distros and many different configurations, starting with the main "shell".

I'm convinced that your problem is `zsh`, otherwise I can't explain these errors. 

Into each AppImage exists a file named "AppRun", a shell script `#!/bin/sh` containing many environment variables (`$PATH`, `$LD_LIBRARY_PATH`...). I'm trying to learn more about "zsh" right now, maybe this is an issue related to the compatibility between the shell scripts with "bash" and "sh" versus "zhs". Maybe this is a crap, however try to set your configuration files, or switch back to "bash".

If not, try to edit the AppRun yourself and merge a PR to these repositories:

    ./*AppImage --appimage-extract
    nano ./squashfs-root/AppRun
then let me know what you did to made it work for you, so I'll try to share ideas with you to made the Appimages work with both "bash" and "zsh".

Cheers

**Comment by newyorkthink** [comment]
hi, i test , is not about zsh or bash

**Comment by newyorkthink** [comment]
![image](https://github.com/ivan-hc/KDE-utils-appimage/assets/87791643/c493aec7-4aa7-4509-a3ee-af5c571e8951)

**Comment by newyorkthink** [comment]
i download new version audcious, and i change bash ,it just Segmentation fault again

and i change zsh

and it Segmentation fault too

**Comment by newyorkthink** [comment]
i os is :kali linux is like debian.
![image](https://github.com/ivan-hc/KDE-utils-appimage/assets/87791643/af1f0f36-9d01-414f-95a6-c0b3e4776bf2)

**Comment by newyorkthink** [comment]
i not have desktop env. 
my system just 803 packages, not have gnome, not have kde, not have xfce , and not have i3wm

i just build i3wm to appimage :)
![image](https://github.com/ivan-hc/KDE-utils-appimage/assets/87791643/08600f58-f952-46bf-82d0-2137ebce3378)

so , ”My system is highly lightweight.“

**Comment by newyorkthink** [comment]
![image](https://github.com/ivan-hc/KDE-utils-appimage/assets/87791643/677e9b46-7fe7-4435-815b-92dbdb348a7f)

i cannot rebuild :(

❯ ./squashfs-root/AppRun
zsh: segmentation fault  ./squashfs-root/AppRun

**Comment by ivan-hc** [comment]
> i os is :kali linux is like debian.

No, Kali Linux is based on Debian but it is oriented to penetration testing and security porpouses... is not a good for desktop usage

> i not have desktop env.
my system just 803 packages, not gnome, not kde, not xfce , and not i3wm

so you're using a minimal configuration on a distro that has less functionalities of the one it is based on? Genial!

My AppImages also rely on system librasies, I wrote in the Apprun 

    export LD_LIBRARY_PATH=/lib/:/lib64/:/lib/x86_64-linux-gnu/:/usr/lib/:
this means that the AppImage expect that you have some system libraries on the host, or this will not work. You can perform your tests by reading https://bnikolic.co.uk/blog/linux-ld-debug.html

Finally we know the issue, this is a problem of Kali Linux, not of the Appimages themself (or at least they are not built to include all the necessary stuff to made them work everywhere, I wont do that, for issues of space used / tools available to build them / built times... the Archmages should fix that, but it takes a lot of studying even those before releasing them... and I'm alone, as always). 

Two are the things:

1. install all the stuff that can made Kali Linux a distro that works normally (for example, Audacious expects you have GTK3+ installed);
2. use another distro, Kali Linux is not for common use because it has not all the stuff that other desktop/server-oriented distros have out of the box.

Closed.
